chipsalliance/UHDM

Makefile

* generating API
* build and run unittest
* add `make clean`

Separate out various tasks in the Makefile.

---

headers/design.h
headers/module.h
model_gen.tcl

From https://google.github.io/styleguide/cppguide.html
* Names in member variables shall be foo_ (not m_foo)
* getters that don't modify anything should be const.
Also, getters should not start with get_ (such as get_foo()),
but named foo(). However currently the name conflicts with a #define,
so that needs to be changed separately if possible.

Use C++ styleguide conventions.

---

Makefile
headers/design.h
headers/module.h
include/vpi_uhdm.h
model_gen.tcl
src/vpi_user.cpp
templates/class_header.h
templates/vpi_user.cpp

More improvements following style-guide
https://google.github.io/styleguide/cppguide.html
* Member names of struct: don't use special notation
(such as m_foo or foo_). Since these are implicitly public,
they are to be seen as directly accessed variables.
* Class name: make Upper-case (currently only BaseClass, for
the generated ones, the yaml file needs changing).
* In the derived classes: use 'final' (for now until we run
into to deeper hierarchies).

Styleguide improvements.

---

headers/containers.h
headers/design.h
model_gen.tcl
src/main.cpp
src/vpi_user.cpp

Unless really needed, using typedef on pointers and reference types
is reducing readability because very crucial information useful for
the reader of the code is hidden behind an opaque type. Using '*' and
'&' directly gives the reader the necessary clues.

Don't typedef pointer and reference types.

---

headers/design.h
include/vpi_uhdm.h
model_gen.tcl
src/vpi_user.cpp
templates/vpi_user.cpp

Getter methods that are marked const should also only return
const pointers so that the intent ('nothing is changed') is
preserved (if we return a non-const pointer, we can modify internals
of the object).
Add slight changes where they are used.

Use const where possible.

---

model_gen.tcl
templates/vpi_user.cpp

clutter of a new-call casted to vpiHandle.
While at it, add const where appropriate and order headers according
to style-guide (c-system headers, c++ system headers, project headers).

vpi_user.cpp: Use a NewHandle() function to minimize the visual

---

tests/test1.cpp
tests/test2.cpp
tests/test3.cpp
tests/test4.cpp
tests/test_helper.h
tests/test_listener.cpp

needs and use namespace where needed)
o Make intendntation of all tests uniform.
o Order headers according to style-guide: system headers first,
then project headers.
o sort headers alphanumerically (makes them easy to find and prevents
merge conflicts)

o Make test_helper.h self-contained (include all the headers it

---

Makefile

installation, not the system one. Fixes #121

Link to correct capnp: we want the one that is in the surelog

---

CMakeLists.txt

This changes two things
* Run CMakeLists through [cmake-format](https://github.com/cheshirekow/cmake_format) so that we can have a 'canonical' representation that results in the least amount of merge conflicts.
* Do dependency globbing using file(GLOB...) as this allows cmake to generate build files for tools that don't depend on shell-globbing (such as [Ninja](https://ninja-build.org/)).

Cmake format globbing

---

CMakeLists.txt

We don't run them and they generate link issues in some
contexts.

Disable capnproto tests to build.

---

model_gen.tcl

There was a mix of space and tab which looked different in the
editor depending on tab-width settings.
Add (emacs-) editor settings for the editor to automatically
pick up the rules.
While at it: remove trailing whitespaces.
Fixes #195

Unify indentation in tcl file to always be 4 spaces.

---

CMakeLists.txt
templates/Serializer_restore.cpp
templates/Serializer_save.cpp

Issue #210
Add windows support
Resolution
Code successfully builds using VS2017 compiler.
Other highlights -
* Update CMake file to use transitive dependencies so parent project
don't have to include all this project's dependencies explicitly.
* Turned off some of the warnings generated by the VC compiler
Known Issues
Runtime issue when loading saved uhdm archive.

Issue #210 Add windows support

---

templates/Serializer.h
templates/Serializer_restore.cpp

Remove trailing whitespaces in the process.

Use const reference instead of copying a string in a parameter.

---

tests/dump.cpp

When --elab is set, always output both, the original restore and

---

model_gen/model_gen.tcl
templates/vpi_visitor.cpp
templates/vpi_visitor.h

The visit_object function was using > 350kiB stack due to
a lot of local string operations and temporary strings
also resulted in larger run time.
Changed to use streams; now < 16kiB stack usage and
possibly a lot faster.

vpi_visitor: Use less stack.

---

templates/Serializer_restore.cpp
templates/Serializer_save.cpp
tests/test_listener.cpp

Issue #210: Fixed serialization crash on windows.
Final commit to get things working on Windows.
Highlights -
* Open the file for serialization in binary mode (default on windows
happens to be text). Be explicit.
* Passing a null pointer to an output stream is ambigious.
Section [2003: 27.6.2.5.4]:
template<class traits>
basic_ostream<char,traits>& operator<<(basic_ostream<char,traits>& out, const char* s);
3. Requires: 2 is non-null.
With this commit Windows builds are fully functional with all tests
passing.

Issue #210: Fix serialization crash on windows

---

CMakeLists.txt

Issue #210
Revert 207f0301065d5491de8df8d9b845fb9347449ed3
This bring back the changes introduced in
5f1b30b2f186dd7bf61370634703cf776b6b6e4d plus a few tweaks.
Highlights -
Generate output files in location where the dev tools expect
instead of moving them to custom location. Rationale being that
dev tools work better when the files aren't moved around.
Visual Studio fails to find the generated test binaries if
they aren't in the expected location. Plus, on windows, CMake
works in multi-configuration mode and so having a single "dist"
folder doesn't work well.

Issue #210: Revert 207f0301065d5491de8df8d9b845fb9347449ed3

---

CMakeLists.txt

Added UHDM_BUILD_TESTS so that in other projects that use this
(e.g. Surelog) we can choose to not expliictly run the sub-project's
tests.

Simplify the way how to add tests. Add option to disable tests.

---

CMakeLists.txt
Makefile
README.md
tests/test-dump.cpp
util/uhdm-dump.cpp

Dumping uhdm is a critical part of working with uhdm, so
let's make this a toplevel binary, installed in $PREFIX/bin/uhdm-dump.
Previously, the testing binary used in tests/dump.cpp was used for that,
but let's keep that just a simple round-trip test.
Additional context: not only makes it sense in this context, but also
in Surelog, in which we'd like to disable building UDHM tests, but still
need a binary to dump uhdm.

Make uhdm-dump a toplevel utility binary.

---

model_gen/generate_elaborator.tcl
model_gen/model_gen.tcl
model_gen/vpi_reverse_map.tcl

No semantic code changes, just whitespaces.
This is a baseline so that future changes don't look cluttered
with random lines changed.
This is the result of the .editorconfig trim_trailing_whitespace
configuration applied.

Remove trailing spaces and fix some smallish indentation.

---

model_gen/model_gen.tcl
templates/vpi_user.cpp

The base class offers a few properties, such as VpiLineNo() or
VpiFile() that can be handled once in vpi_get() and vpi_get_str(),
so that the remaining function body only has to worry about the
'non-standard' properties.
* Changed vpi_get64()/vpi_get() to handle VpiLineNo() and VpiType().
* All other properties are output in a similar way as before,
but in a slightly easier human-browsable switch/case form.
* Since get64 and get are the same right now, just one one function
call the other so that we don't duplicate code.
* vpi_get_str handles VpiFile, VpiName and VpiDefName from the
base-class, then deals with remaining 'manually'.
There are still a lot of properties that have to be handled
manually, but future work could consider having property-specific
interfaces …

vpi_user: handle some properties from the base-class once.

---

CMakeLists.txt
templates/vpi_uhdm.h
templates/vpi_user.cpp
tests/vpi_value_conversion_test.cpp

Testing revealed that the parsing of a real value was actually
parsing an integer instead. Fixed (atol() -> atof()).
Also IWYU: vpi_uhdm.h was missing the vector header.

Add test for value conversion; fix bug in String2VpiValue().

---

templates/vpi_user.cpp
tests/vpi_value_conversion_test.cpp

While at it, simplify and speed up VpiValue2String() and String2VpiValue().

Make symbolic scalar parsing work; output scalar symbolic names.

---

model_gen/model_gen.tcl
templates/vpi_listener.cpp
templates/vpi_uhdm.h
templates/vpi_user.cpp

In code generation, replace NewHandle() with NewVpiHandle()
where possible, to see the remaining parts to address.
No functional change otherwise.

Document NewHandle() memory-leak situation and path forward.

---

CMakeLists.txt

While we don't use optimization for the bulk of the generated files,
because they are slow to compile, SymbolFactory is quick to compile
with optimization and yields > 4x speedup for SymbolFactory
operations (on my laptop, Blackparrot2 compile spent
2.58s vs 11.8s in SymbolFactory::Make)).
So selectively switch on optimization for that file.

Switch on optimization for SymbolFactory.

---

CMakeLists.txt

Optimization had been switched off for all code except for
one that really needed optimization.
Let's do it the opposite: compile all files with optimization
but excempt a few that take excessively long to compile. This
also makes it very explicit which can benefit the most by
different code generation.
Compilation time roughly doubles on my machine with this change,
but the runtime also is significant: a uhdm-dump is about 3x
faster (On my machine a dump of blackparrot takes 19 seconds vs. 65 seconds).
Given that with ccache we won't really see increased compilation times
after the first compile, this looks like well worth it.

Optimization: on for all except a few.

---

CMakeLists.txt

Since the optimization was done always, it also hurt the debug
build. Let's do no optimization on these files until we have figured
out how to make them compile fast.

Reduce optimization levels of slow-to-compile files further.

---

model_gen/model_gen.tcl

The default Tcl exec has the unfortunate feature to fail when
the command in question outputs on stderr, switch this off.

Make sure the Tcl script does not stop if capnp emits a warning.

---

model_gen/model_gen.tcl
templates/uhdm_types.h

* Change typedef enum {} foo C-ism to enum foo {}.
* Fix generated indentation of the define enums.

UHDM_OBJECT_TYPE: name enum directly, no typedef. Add indent.

---

CMakeLists.txt
model_gen/file_utils.tcl
model_gen/generate_elaborator.tcl
model_gen/model_gen.tcl

This reduces churn of what the compiler has to re-compile a lot
when doing small changes to code generation and object models:
only files that don't exist or whose output actually change
are be overwritten.
Tested:
touch model/*.yaml ; make
The tcl script is run, but it does not generate any changed artifacts,
so no files are recompiled.

Only write generated files if they actually changed.

---

model_gen/model_gen.tcl

Without constructor, the trivial types such as integers and
pointers have undefined values.

Make sure members are properly initialized.

---

CMakeLists.txt
model_gen/generate_elaborator.tcl
model_gen/model_gen.tcl
templates/BaseClass.h
templates/clone_tree.cpp

* The original implementation used a gigantic switch/case
statement with lots of C-style casts.
C++ offers an opportunity to do that type-safe and more readably.
* Impelement a BaseClass::DeepClone() method instead, essentially
with the same implementation, but for each class separately.
* Using covariant return types, this is now also type-safe and
avoids most of the casts (except the dynamic casts).
* Compilation time for clone_tree.cpp went down from many minutes
in -O3 to < 30 seconds.
So it could be removed from the optimization excempt list in
cmake.
* I expect clone_tree() to go away in favor of directly calling
DeepClone(), but left it in for now for backward compatibility.
(... with a one-line implementation).
As an example how it looks, here is a snippet from the previous …

Implement clone_tree() using overloaded BaseClass::DeepClone() (and fixing a bug ?)

---

model/ref_obj.yaml
templates/uhdm.h

Non standard extension like these are made to be able to keep an abstract representation of the design without the need to bit blast all data members and leave it to the client application to decide if bit blasting is required.

Add non-standard tag for struct member reference

---

model_gen/model_gen.tcl

Even if the schema didn't change, the UHDM.capnp.h file might
have been not there for other reasons. In that case, run capnp.

Regenerate UHDM.capnp.h if it got lost.

---

CMakeLists.txt

Also, sort all the generated sources, so that it is easier to pinpoint missing ones.

Add missing generated src from CMakeLists

---

model_gen/model_gen.tcl
templates/BaseClass.h

* VpiType() is defined in every class implementation. Make
the BaseClass declaration abstract to make sure it really happens
everywhere.
* VpiLineNo() setter and getter are implemented in every class
the same way. Implement it in the base class.

Make VpiType() abstract in BaseClass; implement VpiLineNo() once.

---

model/import.yaml
model/models.lst
templates/vpi_visitor.cpp

This pull request introduces a UHDM-specific node type to keep track of imported symbols. This is needed for some tools (like Verilator) to resolve unqualified identifiers.

Add nodes for import statements

---

CMakeLists.txt

macOS does not have library "rt" and does not need it. Removing "PUBLIC rt" for Apple in CMakeLists.txt makes UHDM built successfully on macOS and pass 100% unit tests.

Built and run successfully on macOS

---

.travis.yml

Stability updates for Windows CI build
* Use choco to install packages instead of hardcoding remote paths
(tclsh remote location disappeared and builds started failing)
* Build for x64 platform to be consistent with linux build
* Don't need to install tclsh. Mingw carries a version of tclsh.
* Surelog requires minimum VS2019. Build UHDM also with the same
version to be consistent.

Stability updates for Windows CI build

---

.editorconfig
.github/workflows/main.yml
.gitignore
CMakeLists.txt
Makefile
model_gen/model_gen.tcl
templates/Serializer_restore.cpp
templates/Serializer_save.cpp

Support for CI Builds on GHA
* Includes Linux, MSYS+GCC and Windows+MSVS
* Fixed a few compile errors to support all configurations
* Added a few additional files/folders to ignore
* Don't assume LF for all editors across platforms
* Updated Makefile to support parallel builds

Support for CI Builds on GHA

---

model_gen/model_gen.tcl

As discussed in #363, `cygpath` is used for fixing the addition of `capnp_path` to the PATH, by converting from windows style to unix style.

model_gen: fix capnp_path on MINGW (MSYS2)

---

model_gen/model_gen.tcl
templates/class_header.h

Some of the classes generated by `model_gen.tcl` have their destructors marked as `final`. Because the classes themselves aren't `final`, during compilation `clang` outputs lots of these warnings:
```
./../image/include/uhdm/headers/constr_if_else.h:40:31: warning: class with destructor marked 'final' cannot be inherited from [-Wfinal-dtor-non-final-class]
```
This PR resolves the issue by adding the `final` keyword to the class declaration, which causes the warning to disappear.

Mark final classes as final

---

templates/BaseClass.h

These functions should have been const (to avoid having const_cast sprinkled all over the code).

Make a few get functions be const

---

model_gen/model_gen.tcl
templates/ElaboratorListener.h
templates/Serializer.h
templates/Serializer_restore.cpp
templates/Serializer_save.cpp
templates/VpiListener.h
templates/class_header.h
templates/clone_tree.cpp
templates/clone_tree.h
templates/group_header.cpp
templates/group_header.h
templates/uhdm.h
templates/uhdm_forward_decl.h
templates/vpi_listener.cpp
templates/vpi_user.cpp
templates/vpi_visitor.cpp
templates/vpi_visitor.h

In the implemtntation compilation units, put the corresponding
header first to easily find incomplete header inclusions.

IWYU: Make headers self-contained.

---

CMakeLists.txt
model_gen/generate_elaborator.tcl
model_gen/model_gen.tcl

Right now, it behaves just as the current code, but with this,
it will be possible to generate code out-of-tree as a preparation
to make it a more hermetic build.

Make it possible to choose where code is generated into.

---

model_gen/model_gen.tcl
templates/class_header.h
templates/uhdm.h
templates/uhdm_vpi_user.h

Move the defines from uhdm.h into separate uhdm_vpi_user.h
This is in preparation to make headers full self-contained.
Issues #59

Break out VPI defines needed in UHDM.

---

model_gen/model_gen.tcl
templates/class_header.h

In generated classes, often pointers referencing other
UHDM types are used, yet they were not included nor
forward referenced; that means the headers only would
work 'by accident' if used in a particular include
sequence. Add necessary forward declarations.
Issues #59

Forward declare referenced types.

---

templates/group_header.cpp

Generated code can generate errors with trailing newlines. This creates a mess in error reports when the message is concatenated within some some larger message. Newlines are an output format thing, shouldn't be part of the message content itself.

Some errors have trailing newlines

---

model_gen/model_gen.tcl
templates/ElaboratorListener.h
tests/listener_elab.cpp

Use 'override' consistently.

---

.github/workflows/main.yml
tests/full_elab.cpp
tests/test-dump.cpp
tests/test-util.h
tests/test1.cpp
tests/test2.cpp
tests/test3.cpp
tests/test4.cpp
tests/testErrorHandler.cpp
tests/test_classes.cpp
tests/test_listener.cpp
tests/test_process.cpp
tests/test_tf_call.cpp

Tests should only access directories explicitly made available
for temporary files by the test harness. Add a simple function
that is checking for common environment variables TEST_TMPDIR,
TMPDIR and then fallback to /tmp.

Don't clobber source directory with test outputs.

---

CMakeLists.txt

Setup include directories correctly so they get included in the
generated config file. Hide private include directories and make
relevant/necessary directories public with proper install prefix.

Issue #1526: Using Surelog as external project dependency

---

CMakeLists.txt
model_gen/model_gen.tcl

**DON'T MERGE INTO SURELOG YET** (that actually also requires fixing #483)
Right now, we still in stall in $PREFIX/include/uhdm/include
and $PREFIX/include/uhdm/headers, but this is the
preparation to do that all from the build/ directory.
Issues #484

Prepare installation of headers in single location.

---

CMakeLists.txt

There is some use-after-delete or similar issue going
on; since this is only used in the context of #480,
disable for now.

Disable garbage collect test for now.

---

CMakeLists.txt
model_gen/model_gen.tcl

Invoking the capnproto tool is fragile in the tcl-script as it has
to do all the platform specific things that are otherwise nicer
solved in cmake.

Move invocation of capnproto tool out of model_gen.tcl to build system

---

model/instance_item.yaml
model/operand_group.yaml
model/simple_expr_use_group.yaml
model/variables_operation_group.yaml

class_refs that refer to obj_def and vice versa.

Fix-up some obj_ref/class_ref mix-ups.

---

CMakeLists.txt

Only add googletest submodule when tests are enabled.

---

model_gen/model_gen.tcl
scripts/classes_h.py
scripts/serializer.py
scripts/vpi_user_cpp.py
templates/BaseClass.h
templates/ElaboratorListener.h
templates/ExprEval.cpp
templates/Serializer.h
templates/Serializer_restore.cpp
templates/Serializer_save.cpp
templates/SymbolFactory.cpp
templates/SymbolFactory.h
templates/clone_tree.cpp
templates/group_header.cpp
templates/uhdm_types.h
templates/vpi_uhdm.h
templates/vpi_user.cpp
tests/full_elab_test.cpp
tests/listener_elab_test.cpp
tests/vpi_listener_test.cpp

Memory Optimization Pass
Use std::string_view in place of std::string in SymbolFactory.
Updated all code generation scripts to use std::string_view.
Revert "Revert "Memory Optimization Pass""
This reverts commit 723ef9d224f1f9d87e774148afc9ca17161f00ef.

Memory Optimization Pass

---

.github/workflows/main.yml
CMakeLists.txt
Makefile
model_gen/model_gen.tcl
scripts/classes.py
scripts/serializer.py
scripts/vpi_listener.py
scripts/vpi_user_cpp.py
scripts/vpi_visitor_cpp.py
templates/BaseClass.h
templates/class_header.h
templates/uhdm_types.h
templates/vpi_listener.cpp
templates/vpi_user.cpp
templates/vpi_visitor.cpp
tests/vpi_listener_test.cpp

Modularization PAss 2
Take model class hierarchy into account when generating code for
vpi_listener, vpi_user and vpi_visitor. Also, the order of
listen/visit callbacks are in the same order as the model's
definition.
NOTE: This implementation changes the order of member processing.
Previous implementation used to visit/listen member of the most
concrete class before doing it for base. This implementation does
it in reverse i.e. the base classes are processed before the most
derived class.

Modularization Pass 2

---

CMakeLists.txt

Use precompiled headers to improve build times.
Initial numbers look very promising with Windows showing
over 70% improvement on build times.
Gotcha - Certain files have different optimization flags at
the moment and those differ from the ones the precompiled header
is built with. This shows up as an issue with clang on MacOS but
none of the other platforms. Resolution is to disable use of
precompiled headers for those certain files (unfortunately, those
are the ones that can benefit the most with use of precompiled
header).

Use precompiled headers to improve build times.

---

templates/BaseClass.h
templates/Serializer.cpp
templates/SymbolFactory.cpp
templates/SymbolFactory.h
templates/vpi_uhdm.h

Fixing allocation life-time issues
* Serializer::symbolMaker was never getting purged between Save &
Restore. This is _not_ a leak, per se, but the recorded amount of
memory used is significantly higher.
* uhdm_handle allocations are mismanaged. They could be allocated by
Serializer::uhdm_handleMaker, and be recorded as part of it in a
vector but this vector never gets emptied. The created instance are
deleted using vp_release_handle. Current solution (stop tracking as
part of the factory) is not optimal but fixes the consistently
growing vector issue.
* Serializer::anyVectMaker was never getting emptied as part of
Serializer::Purge call.

Fixing allocation life-time issues

---

model_gen/model_gen.tcl
model_gen/parse_model.tcl

@hs-apotell, please fix this in your Python version too.
Group checks were not recursively checking group members (Maybe you fixed that already).

Transitive group member

---

scripts/classes.py
templates/BaseClass.h
templates/Serializer_restore.cpp

Avoid declaring additional namespaces in public headers.
Signed-off-by: Henner Zeller <hzeller@google.com>

Don't pollute global namespace with fs shortcut.

---

.github/workflows/main.yml

windows-latest on GHA now defaults to Window Server 2022 and doesn't have VS2019 preinstalled.

Upgrade VS2019 to VS2022

---

.github/workflows/main.yml
INSTALL.md

This better documents what needs to be done. However, we it still would
be good to have a check in cmake to make sure that the orderedmultidict
is installed.
Signed-off-by: Henner Zeller <hzeller@google.com>

Improve install experience: system provide all the Python depdendencies

---

CMakeLists.txt

chipsalliance/UHDM#640: Add a check to find required python packages
Added a check to find 'orderedmultidict' and repport an error if the
module isn't found.

chipsalliance/UHDM#640: Add a check to find required python packages

---

scripts/capnp.py
scripts/serializer.py
templates/Serializer.h
templates/Serializer_restore.cpp
templates/Serializer_save.cpp

Rework serialization to reduce template specialization and thus reduce generated binary size.
For release builds, this change reduces the binary sizes by ~20%.
Instead of dumping every field in the capnp schema for each class, subclasses carry only a pointer to the base schema. Thus, a class, say `attribute`, always loads data from a schema named `Attribute` and so no template specialization is required.
@alaindargelas @hzeller This is only a prototype of the change and for either of you to play around with if you find this worthwhile. If the change passes any/all checks, then I can clean up and create a PR for merge.

Reduce template specialization

---

scripts/VpiListener_h.py
scripts/vpi_listener.py
templates/ElaboratorListener.cpp
templates/ElaboratorListener.h
templates/ExprEval.cpp
templates/SynthSubset.cpp
templates/SynthSubset.h

Remove listen_/enter/leave for class_def
Remove public API and enter/leave listener callbacks for class_def
models.
These methods give the false impression that those callbacks will
be called while walking the design hierarchy. The callbacks were
meant to be called iff the specific listen_<class_def> API was
invoked. Not worth the ambiguity.
P.S. This has infact caused a bug in ElaboratorListener & SynthSubset
implementations where enter/leave functions were implemented for
class_def but those functions will never be called.
Also, fixed a few build warnings in ExprEval
P.S. This is a potentially breaking change since it modifies the public
VpiListener.h file and removes a few publicly available listen_xxx
APIs.

Remove listen_/enter/leave for class_def

---

model/design.yaml
scripts/VpiListener_h.py
scripts/vpi_listener.py
scripts/vpi_visitor_cpp.py
templates/ElaboratorListener.cpp
templates/ElaboratorListener.h
templates/ExprEval.cpp
templates/SynthSubset.cpp
templates/SynthSubset.h
templates/clone_tree.cpp
templates/group_header.cpp
templates/group_header.h

Improve UHDM readability
* Move vpiTopModules iteration after all definitions have been visited
* Make vpiInstance a shallow visit so enter gets called but the instance
itself doesn't stepped in. This reduces the depth of the tree being
printed and also reduces the call-depth.
* Make group_header arguments const

 Improve UHDM readability

---

scripts/vpi_listener.py

Issue#662: Fix warnings
Generate private method bodies in vpi_listener only if the model has
sub-models or if the model itself is an obj_def. Prevents creating
private functions for models that are declared as class_def but has
no associated obj_def.

Issue#662: Fix warnings

---

scripts/classes.py
scripts/vpi_listener.py
scripts/vpi_visitor_cpp.py
templates/ElaboratorListener.cpp
templates/ElaboratorListener.h
templates/ExprEval.cpp
templates/vpi_visitor.cpp

vpi_visitor & vpi_listener logic update
* vpi_listener
** vpiExtends cannot be safely ignored since there could be only a
single reference to it. Ignoring would mean there is never a
entry/leave call for it.
** Avoid entry/leave for vpiProgram, vpiPackage, and vpiUdp when
referred as a member reference from other objects.
* vpi_visitor
** Show vpiParent in the output for bit_select & part_select
** Never use shallow for ref_obj - without the vpiActual the reference
itself is pointless
** Similar update for vpiInstance, vpiModule, vpiInterface, vpiUse,
vpiProgram, vpiClassDefn, vpiPackage, and vpiUdp.
** Attempt to show all the information at the outer level but shallow
in inner level of the hierarchy (basically, flattenning the tree a
bit so it's easier to visually parse).

vpi_visitor & vpi_listener logic update

---

templates/Serializer.cpp
templates/Serializer.h

During initialization the setID function consumes a lot of cycles hashing the BaseClass pointer.
This change reduces the uhdm read time by 22%.

Speeding up UHDM deserialization

---

Makefile

Also, resolve shell from /usr/bin/env as it might not
be available in /bin

make clean: also clean dbuild.

---

templates/UhdmListener.cpp
templates/UhdmListener.h

Adding {enter|leave}Any callbacks to allow subclasses to implement
a single function instead of every possible function. This callback
is useful for implementing pre-processing listeners (like collecting
all objects in model hierarchy).

Adding {enter|leave}Any callbacks

---

CMakeLists.txt
templates/Serializer_restore.cpp
templates/SymbolFactory.cpp
templates/SymbolFactory.h
tests/symbol_factory_test.cpp

Rather, have strings stored in the id2Symbol map, and then
just have string_views pointing to them mapped in the symbol2IdMap.
Use that opportunity to improve the interface of Make() to
take a string_view.

Don't store strings twice in SymbolFactory.

---

tests/symbol_factory_test.cpp

The other tests in this directory use quote (") instead
of angle bracket (<) for inclusion of gtest.h and gmock.h.
Be consistent and do the same in symbol_factory_test.cpp.

Be consistent with inclusion file quoting.

---

model/design.yaml
model/include_file_info.yaml
model/models.lst
templates/uhdm_vpi_user.h
templates/vpi_visitor.cpp

chipsalliance/Surelog#2541: Add include file info model
UHDM::design now provides a list of includes

chipsalliance/Surelog#2541: Add include file info model

---

model/gen_scope.yaml

The VPI Standard has a bug, gen_scope do allow to have in-scope function declaration, all simulators support it.
Adding that property.

Gen scope to support task_func

---

scripts/UhdmListener.py

Update to the way callstack is maintained in UdhmListener
In the previous implementation, the callstack was updated only when any
of the members of object would receive enter/leave callbacks. That logic
introduces problems for cases where additional listenXXX calls are made
from within the enter/leave callbacks. The callbacks never see the
callstack being updated. As an update, update the callstack before and
after the enter/leave callbacks respectively. The side-effect of this
change is that the top of the callstack will always be the object for
which the enter/leave callback is being invoked. So, to check the
immediate context, the enter/leave callbacks have to check the
penultimate entry on the callstack.
This change is required to implement logic, like Linter, where the order
of …

Update to the way callstack is maintained in UdhmListener

---

scripts/classes.py
scripts/vpi_visitor_cpp.py

Resolving some ref_obj parenting issues
* Show ref_obj's parent in UHDM output as this is critical piece of
information for this specific model. Current logic does not suffice
because it uses the parent's name and more often than not the name is
empty.
* Objects in elaborated model where pointing into the non-elaborated side
as parent.

Resolving some ref_obj parenting issues

---

scripts/vpi_visitor_cpp.py

PR #721 introduces too much bloat (duplicates) in uhdm output.
Print parent shallow for all but _select parent
Also, print parent only for concrete models

PR #721 introduces too much bloat (duplicates) in uhdm output.

---

templates/vpi_visitor.cpp

Issue chipsalliance/Surelog#2985: Remove 'parent' in uhdm output
The information is now available as an independent field in the hierarchy which includes the id information as well.

Issue chipsalliance/Surelog#2985: Remove 'parent' in uhdm output

---

scripts/vpi_visitor_cpp.py
templates/vpi_visitor.cpp

Parenting in UHDM output
Moving the parent information from being inlined to actually visiting
the parent. This is important for models like ref_obj which are unique
for each instance and carry important information like the 'actual'
parent and vpiActual.

Parenting in UHDM output

---

scripts/vpi_visitor_cpp.py

Issue chipsalliance/Surelog#3012 Recent vpiParent change makes
debugging difficult
vpiParent visitation was meant to be shallow except for ref_obj. But
that exception causes ripple down the stream because vpiActual still
ends up being non-shallow. Ensure that the entire ref_obj visitation is
shallow.

Issue chipsalliance/Surelog#3012 Recent vpiParent change makes debugging difficult

---

scripts/capnp.py
scripts/classes.py
templates/BaseClass.h
templates/Serializer.cpp
templates/Serializer_restore.cpp
templates/Serializer_save.cpp

Removed BaseClass::UhdmParentType
For some unknown reason (probably historical remnant) the
BaseClass::vpiParent is stored differently in the cache compared to all
other references to BaseClass. BaseClass::vpiParent used
BaseClass::vpiParentType and index for caching, and other BaseClass
references used ObjectIndex as setup in capnp.
Removing the former approach to generalize how all references are
stored for consistency. Fixed up Serializer Save/Restore accordingly.

Removed BaseClass::UhdmParentType

---

templates/BaseClass.h
templates/Serializer_restore.cpp
templates/Serializer_save.cpp

The FactoryT does not have a need to keep the list contiguously in
memory, so we can use deque, avoiding unnecessary re-allocs.
This allows the memory allocator to not worry about providing many large contiguous regions, which could contribute to an improved situation for https://github.com/chipsalliance/Surelog/issues/2962

Use a std::deque instead of a std::vector to keep track of allocated objects

---

templates/vpi_visitor.cpp

chipsalliance/Surelog#2962: Flush often
With large designs, visitation logic can end up buffering too much with
no progress reported on screen. Switching to flush often. This also
helps with keeping the memory requirement down for large designs.

chipsalliance/Surelog#2962: Flush often

---

templates/vpi_visitor.cpp
templates/vpi_visitor.h
tests/classes_test.cpp
tests/error-handler_test.cpp
tests/expr_reduce_test.cpp
tests/full_elab_test.cpp
tests/garbage_collect_test.cpp
tests/listener_elab_test.cpp
tests/module-port_test.cpp
tests/process_test.cpp
tests/statement_test.cpp
tests/test_util.h
tests/tf_call_test.cpp
util/uhdm-dump.cpp

* Changing the flushing on each output creates a huge slowdown
and leaves the user with no choice. If the caller would like to
have that behavior, it should be done outside of this function.
* As looking at Surelog shows, the visitor that returns the string is
mis-used 100% of the time. Let's not provide that rope.
* Add the convenience function that retunrs a string in the
test_utils.h for local use in the unit tests.
Context:
https://github.com/chipsalliance/UHDM/pull/743
https://github.com/chipsalliance/Surelog/issues/2962

Let the stream handle its own flushing. Only use method returning string in tests 

---

scripts/vpi_visitor_cpp.py
util/uhdm-dump.cpp

Using std::endl will flush the stream with each line which is
definitely not what we want when dumping out a large design.
This speeds up uhdm-dump significantly.

Fix more places that overzealously flush the stream.

---

templates/VpiListenerTracer.h
tests/vpi_listener_test.cpp

The header relied on forward declared classes, but since it actually
accesses members (VpiLineNo() etc.), it needs a full declaration of
these.

Make VpiListenerTracer.h be self-contained.

---

scripts/classes.py

Issue chipsalliance/Surelog#3077 - Include gates and udps in non-elaborated tree
Don't clone udp_defn. Bind any existing cloned one or use the one from
source i.e. one that is being cloned.

Issue chipsalliance/Surelog#3077 - Include gates and udps in non-elaborated tree

---

templates/clone_tree.cpp

pushing instead of popping var in array iterator vars

expensive typo

---

.github/workflows/main.yml

Handle CI subcommand failures correctly
Unlike bash, Windows scripts don't fail if one of the subcommand in the
batch fails. Result from each such command has to explicitly be checked
and bubbled up appropriately.

Handle CI subcommand failures correctly

---

scripts/UhdmListener.py
tests/uhdm_listener_test.cpp

Update to callback logic in UhdmListener
In previous implementation, specific vpiXXX listen invocations were
skipped. This has been found to be a problem since there are cases where
there is only one such edge in the tree and that is being skipped.
Instead, let the client code deal with duplicate callbacks. The visit
container will track all objects that are already stepped-in to avoid
infinite recursion.

Update to callback logic in UhdmListener

---

scripts/classes.py
scripts/serializer.py
templates/BaseClass.cpp
templates/BaseClass.h
templates/Serializer.cpp
templates/Serializer.h
templates/Serializer_restore.cpp
templates/Serializer_save.cpp

Revert 82fd37f01e508fb839cb1c02b519bf15d825dd8e: Use filesystem where applicable
VpiFile is back to string as it doesn't necessarily always represent a legal filesystem path. Widening the scope of what this represents from a specific local filesystem path to cover scenarios like UNC paths and generic resource ids.

Revert 82fd37f01e508fb839cb1c02b519bf15d825dd8e: Use filesystem where applicable

---

CMakeLists.txt

The UDHM.capnp.h is included without path in the UHDM.capnp.c++ implementationa as well as in our serializers.
Add that to the needed include path. Currently it only works if we consider an implicit -I.
Also remove include to third_party/UDHM/src, which looks like some copy-paste issue from somewhere else ?

The generated UHDM.capnp.h is in generated/src, point -I to it.

---

CMakeLists.txt

Looks like in some environments this helps it to be more robust.

Be explicit with the src prefix in the capnp compile.

---

tests/module-port_test.cpp
tests/statement_test.cpp

If testing::TempDir() is the same for all tests (likely), this otherwise can result in collisions if tests are run in parallel.

Make sure that test-files written are unique between tests.

---

scripts/classes.py
templates/BaseClass.h
templates/ExprEval.cpp

Accept std::string_view as argument instead of std::string&. Also, 
* check for invalid value post reduction before using it.
* fixed a few warning messages.

Accept std::string_view as argument instead of std::string&

---

Makefile

This will help discover if tests are truly independent (e.g. not modify the same files in TempDir()).

Tell unittest ctest to run tests in parallel.

---

scripts/classes.py

Include vpiDefLineNo & vpiRefXXX in ignore list for uhdm compare
Differences in these variable don't make the UHDM tree logically different.

Include vpiDefLineNo & vpiRefXXX in ignore list for uhdm compare

---

CMakeLists.txt
scripts/generate.py
templates/ExprEval.cpp
templates/NumUtils.cpp
templates/NumUtils.h
templates/UhdmLint.cpp
templates/vpi_uhdm.h
templates/vpi_user.cpp
tests/vpi_value_conversion_test.cpp

Swap out std::strtoxxxx in favor of std::from_chars for portability
* Implemented NumUtils to contain all number related utility functions
* Remove use of posix functions like strdup, strstr & strcasecmp (replace with custom implementation as there are no equivalent in C++)
* Some of the vpi functions now accept std::string_view instead of std::string
Known Issues:
Number parsing errors are largely ignored, to keep the behavior the same as previous implementation. Accounting for parse errors results in regression test failures. Will need to revisit these individually as a follow up.

Swap out std::strtoxxxx in favor of std::from_chars for portability

---

templates/NumUtils.cpp
templates/NumUtils.h

Issue chipsalliance/Surelog#3385: Favor namespaces over static classes
Use namespace instead of static classes to collect static functions.

Issue chipsalliance/Surelog#3385: Favor namespaces over static classes

---

.github/workflows/main.yml

Upgrade external actions
Also, working around another reported issue https://github.com/actions/runner-images/issues/6817
So, avoid using _brew update/upgrade_ in combination with use of _setup-python_.

Upgrade external actions

---

scripts/classes.py

Fix a bug in compare logic
'group_ref' was being ignored from comparison and param_assign uses that as the key for LHS & RHS.

Fix a bug in compare logic

---

scripts/ElaboratorListener_cpp.py
templates/ElaboratorListener.cpp
tests/listener_elab_test.cpp

This improves compatibility in case the map type is not std::map.

Use ComponentType::value_map instead of std::make_pair

---

CMakeLists.txt

By default, keeps using third_party/ capnproto, but allows to use the capnroto installed on the system by setting UHDM_USE_HOST_CAPNP=On
This helps UHDM to be packed in distributions.
(So wht do we keep third_party/ ? On Windows, there is no common package manager, so projects there rely more on things to be pulled in together; see discussion in #491).
Fixes: #483

Allow to use native capnproto.

---

include/sv_vpi_user.h
include/vpi_user.h
model/design.yaml
model/gen_scope.yaml
model/instance.yaml
model/instance_array.yaml
model/interface_inst.yaml
model/modport.yaml
model/module_inst.yaml
model/nets.yaml
model/ports.yaml
model/process_stmt.yaml
model/program.yaml
model/tchk.yaml
model/test.yaml
model/variables.yaml
scripts/VpiListener.py
scripts/config.py
scripts/vpi_visitor_cpp.py
templates/ElaboratorListener.cpp
templates/UhdmAdjuster.cpp
templates/vpi_visitor.cpp
tests/listener_elab_test.cpp
util/uhdm-hier.cpp

Issue #859: vpiModule & vpiInterface are part of standard
Follow up to a previous change where vpiModule & vpiInterface were renamed to vpiModuleInst & vpiInterfaceInst, respectively. This is flawed and doesn't meet the vpi standard. Reverting the names back to vpiModule & vpiInterface. However, the classes generated against the models remain named module_inst & interface_inst.

Issue #859: vpiModule & vpiInterface are part of standard

---

.github/workflows/main.yml
CMakeLists.txt
Makefile

Sorry for push noise, unfortunately there was a lot of annoying GitHub actions nuances to look at
This PR does a few things:
- fixes a small non-typo "typo" introduced in https://github.com/chipsalliance/UHDM/pull/817. Both [`FindGTest`](https://cmake.org/cmake/help/latest/module/FindGTest.html) and the local `CMakeLists.txt` file reference `GTEST_INCLUDE_DIRS`, but the code used `GTEST_INCLUDE_DIR` (gosh don't we all love CMake 😆). This is allegedly "private" in `FindGTest`.
- Splits the `ubuntu` test to test both vendored-dependency and non-vendored-dependency code paths for cmake (`ubuntu` chosen because it's usually the fastest on GitHub Actions). Can see behavior on my [fork actions](https://github.com/timkpaine/UHDM/actions)
- fixes a codepath in `CMakeLists.txt` that only linked …

Fix system-provided `gtest` use

---

templates/SymbolId.h

Since -DDEBUG is commonly used, it is dangerous to change the layout of an object just because of that - the project using UHDM will now accidentally change the size that is not compatible anymore with the library.
(This might not have detected before as UHDM typically was compiled alongside Surelog with the same flags, but 3rd party applications just using UHDM will break).
Fixes #872

Don't use -DDEBUG to change layout of SymbolId

---

CMakeLists.txt

A handful of `CMAKE_` variables have to become `PROJECT_` variables so that `UHDM` will use its own paths when vendored as a submodule of `Surelog`

CMake fixes for UHDM used as a vendored git submodule

---

CMakeLists.txt
install/UHDM.pc.in

In all our examples, we use `#include <uhdm/foo.h>`, so the base include directory should be $PREFIX/include, not $PREFIX/include/uhdm.
The libraries to link depends on of iwe used USE_HOST_CAPNP. If we compiled and installed from third_party/, we need to include the linking of the libraries from there, otherwise we need to require to use the pkg-config from capnp.

pkg-config: base inc dir; choose libs depending on USE_HOST_CAPNP

---

util/uhdm-dump.cpp

The --version addition messed up the printed paragraph.

uhdm-dump: Fix sequence in printing help.

---

CMakeLists.txt

Project config setup needs to be public to allow transitivity

Project config setup needs to be public to allow transitivity

---

CMakeLists.txt

Reverts chipsalliance/UHDM#912

Revert "Project config setup needs to be public to allow transitivity"

---

CMakeLists.txt

Project config setup needs to be public to allow transitivity.
Also, options with spaces in target_compile_options should be prefixed with SHELL to preserve spaces.

Project config setup needs to be public to allow transitivity.

---

templates/ExprEval.cpp

Noticed while parsing opentitan.

Fix segmentation fault

---

scripts/ElaboratorListener_cpp.py
scripts/classes.py
templates/BaseClass.cpp
templates/BaseClass.h
templates/ElaboratorListener.cpp
templates/ElaboratorListener.h
templates/ExprEval.cpp
templates/UhdmAdjuster.cpp
templates/class_header.h
templates/clone_tree.cpp
templates/clone_tree.h
templates/vpi_user.cpp
templates/vpi_visitor.cpp
templates/vpi_visitor.h
tests/classes_test.cpp
tests/expr_prettyPrint_test.cpp
tests/expr_reduce_test.cpp
tests/full_elab_test.cpp
util/uhdm-cmp.cpp
util/uhdm-dump.cpp
util/uhdm-hier.cpp

Add CloneContext, CompareContext & ElaboratorContext
This is initial change for a larger goal to untie the tight coupling between cloning and elaboration. As it stands today, cloning doesn't work except for the specific case of elaboration.
* Context classes allows for adding additional args to the API without having to change the API itself.
* CompareContext returns the first failed comparison
* CloneContext has no concept of Elaboration to support cloning without elaboration or binding logic
* ElaboratorContext is a subclass of CloneContext that extends the cloning functionality with elaboration.
* uhdm-cmp now prints the first mismatch, if comparison fails.

Add CloneContext, CompareContext & ElaboratorContext

---

CMakeLists.txt
scripts/VpiListener.py
templates/ElaboratorListener.cpp
templates/VpiListener.cpp

Avoid cycles in VpiListener & in ElaboratorListener
* A ref_obj shouldn't point to another ref_obj as its actual_group.
* listenDesign_ clears the visited container between iterating allXXX and topXXX. That removes the top level design as well (which was added by listenDesign) causing infinite loops.
This is found in cases where "$root" is used and the corresponding ref_obj::actual_group points to a design.

Avoid cycles in VpiListener & in ElaboratorListener

---

scripts/serializer.py

Check for null before attempting to save
The issue surfaced in cases where multiple unsupported_typespec got erased. The accumulation of nullptr in allIds_ would return the index of the first such attempt which may not be same for other subsequent ones.

Check for null before attempting to save

---

scripts/classes.py

Issue #979: Casting to wrong type causes crash in Compare function
Added a check in all obj_def implementation to check the corresponding object type before casting.

Issue #979: Casting to wrong type causes crash in Compare function

---

CMakeLists.txt
include/config.h.in
templates/Serializer.cpp
templates/Serializer_restore.cpp
templates/Serializer_save.cpp

chipsalliance/Surelog#65: Deprecate flatbuffers in favor of Cap'n'Proto
Make use of Cap'n'Proto in UHDM public. Also, set the Cap'n'Proto related
output variables in the cache so outer projects can use then without
defining them again.
In cmake terms, make use of Cap'n'Proto in UHDM transitive.

chipsalliance/Surelog#65: Deprecate flatbuffers in favor of Cap'n'Proto

---

util/uhdm-cmp.cpp
util/uhdm-dump.cpp
util/uhdm-hier.cpp
util/uhdm-lint.cpp

It can be difficult to determine that all linking has been done correctly in a build environment by just looking at the generated libraries. A common pattern I've been seeing (e.g. on homebrew, conda, etc) is to run `my-executable --help` which seems to be expected to not have an error exit code. A quick survey of CLIs on my box confirms this pattern >50% of the time, so I propose we use it here. This is also the behavior of the `surelog` command.

make utility executables exit with error code 0 when running --help

---

CMakeLists.txt
Makefile
README.md
cmake/configs/UHDM.pc.in
cmake/configs/UHDMConfig.cmake.in

This PR does two things:
- instead of installing into `lib/uhdm/`, we will install into `lib`. This is the normal method, installing into `lib/uhdm/` has caused problems on both conda and homebrew, and is sure to continue to cause headaches
- we use `SOVERSION` so that `lib/libuhdm.so` is now a symlink, and we install a versioned `lib/libuhdm.so.<major>.<minor>`
Fixes #992 
(I will do a similar PR for Surelog)
---
```
-- Installing: /tmp/uhdm-install/lib/libuhdm.so.1.71
-- Installing: /tmp/uhdm-install/lib/libuhdm.so
```

Remove uhdm libs out of own folder, use soversion (fixes #992)

---

templates/Serializer_restore.cpp
templates/Serializer_save.cpp

The files should be self-contained and include the header that defines the windows-specific O_BINARY.
(Currently that only works accidentally if compiled with cmake)

Make sure serializers include the config.h

---

scripts/UhdmListener.py
scripts/VpiListener.py
scripts/serializer.py
templates/BaseClass.cpp
templates/ElaboratorListener.cpp
templates/ExprEval.cpp
templates/Serializer_restore.cpp
templates/Serializer_save.cpp
templates/SynthSubset.cpp
templates/UhdmAdjuster.cpp
templates/UhdmLint.cpp
templates/VpiListener.cpp
templates/class_header.h
templates/clone_tree.cpp
templates/uhdm_types.h
templates/vpi_user.cpp

Instead of foo use UHDM_OBJECT_TYPE::foo if something is of that type. This does not cover all places yet, but it will allow us to make UHDM_OBJECT_TYPE an enum class at some point and improve type-safety.

Start using scoped enums in many places for readability.

---

CMakeLists.txt

Addressing https://github.com/chipsalliance/Surelog/pull/3828#discussion_r1313727187

Move .capnp file to share to avoid excess stuff in lib, make sure windows .lib and .dll in same dir

---

templates/SynthSubset.cpp

After a recent change to `synth subset checker` we're not able to check if a node belongs to the non-synthesizable set or not, and as a result non-synthesizable parts of this test cause errors:
https://github.com/zachjs/sv2v/blob/764a11af7f861dfbf9e2c40422fe7b02f7a166c2/test/core/struct_part_select.sv
Here's the change in UHDM:
https://github.com/chipsalliance/UHDM/commit/da7e6cfc0d84a3498f8a90ec050f5d57cd128b41
I've observed that we can safely bump the Surelog submodule when we use UHDM without the early return from `SynthSubset::reportError`
I've run tests here: https://github.com/chipsalliance/synlig/actions/runs/6198609315/attempts/1
FYI @kbieganski

do not return early from reportError

---

include/sv_vpi_user.h
model/models.lst
model/prop_formal_decl.yaml
model/ref_typespec.yaml
scripts/capnp.py

Sort capnp factories, ref_typespec, and naming consistency
* Sort the factories in capnp output so comparisons are easier
* Introducing ref_typespec, parallel to ref_obj to reference typespecs
* Enforce naming consistency

Sort capnp factories, ref_typespec, and naming consistency

---

templates/ExprEval.cpp
templates/clone_tree.cpp

struct_net::Typespec could be union_typespec
Removed assumption that the struct_net::Typespec can only be struct_typespec. C-style cast was hiding the assumption.

struct_net::Typespec could be union_typespec

---

include/sv_vpi_user.h
model/class_defn.yaml
model/interface_inst.yaml
model/module_inst.yaml
model/named_begin.yaml
model/named_event.yaml
model/named_fork.yaml
model/package.yaml
model/program.yaml

Add property to track end labels for scopes
P.S. Change in sp_vpi_user.h to include two new properties vpiLabel & vpiEndLabel.

Add property to track end labels for scopes

---

templates/ExprEval.cpp
templates/vpi_visitor.cpp

This PR fixes compilation for newer gcc version by adding missing include.
It also fixes evaluation of `$left`, `$right`, `$high`, `$low` by adding missing `$` when comparing function name.

Fix compilation with gcc 14; Fix evaluation of `$left`, `$right`, `$high`, `$low`

---

templates/SynthSubset.cpp
templates/SynthSubset.h

Simply removing a non-synthesizable construct from the AST can lead to ill-formed parent statements:
Example:
for (int i = 0; .....) 
$fdisplay (...) ;
Would become:
for (int i = 0; .....) 
And crash during Synthesis due to incomplete for loop statement (No actual statement).
Since the null_stmt is not supported in downstream tools, the safest statement is a dummy $display statement to put in place of the non-supported statement.

Safer replacement of non-synth constructs

---

templates/uhdm.h

clang-tidy usually would complain if not a direct header for a particular symbol is included.
The uhdm.h header is meant as a 'catchall' header that provides all the symbols in all the headers is includes. So mark them as such so that toolings understand that this is the intention.
A common way is to use the IWYU pragmas for that:
https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-begin_exportsend_exports

Add IWYU pragmas in header meant to export other headers.

---

templates/NumUtils.cpp
templates/SynthSubset.cpp

It accidentally doesn't make any difference, as this is the last case in that switch, but this removes ambiguity about intention.

Add missing break in switch.

---

templates/ExprEval.cpp

Addresses #1094 
The solution is very ad-hoc. A better solution would be to move `$size` implementation from `ExprEval::size` to where `$high` and `$low` are evaluated, but that section of code is also unused, untested and very likely broken. See https://github.com/chipsalliance/UHDM/issues/1094#issuecomment-2705321758 for more details.

Fix evaluation of $size for array

---

python/UHDM.i
python/tests/test_module.py
templates/ElaboratorListener.h
util/uhdm-dump.cpp
util/uhdm-dump.py
util/uhdm-hier.py

This produces line-identical output with uhdm-dump.cpp (with --elab and --compare) for the few test designs that I have. I've removed the golden file stat print from the CPP as discussed in #1107 
In order to avoid complications with C++ file handles vs Python, we play a trick in UHDM.i to redirect the output to an osringstream and return it to Python. Generally this should be transparent

Adding UHDM dump Python script
