chipsalliance/UHDM

- Makefile
> Set up a minimum of warnings.

- headers/containers.h
- headers/module.h
- headers/uhdm.h
- model/uhdm.yaml
- model_gen.tcl
- src/main.cpp
- src/vpi_user.cpp
- templates/vpi_user.cpp
> support for obj_ref

- headers/module.h
- src/main.cpp
> unittest update

- Makefile
- headers/uhdm.h
- model/cont_assign.yaml
- model/interface.yaml
- model/interface_array.yaml
- model/models.lst
- model/module.yaml
- model/port.yaml
- model/scope.yaml
- model/test.yaml
- model_gen.tcl
- src/vpi_user.cpp
> split yaml model files

- headers/alias_stmt.h
- headers/clocking_block.h
- headers/cont_assign.h
- headers/def_param.h
- headers/design.h
- headers/instance_array.h
- headers/interface.h
- headers/interface_array.h
- headers/io_decl.h
- headers/mod_path.h
- headers/module.h
- headers/module_array.h
- headers/port.h
- headers/primitive.h
- headers/primitive_array.h
- headers/process.h
- headers/scope.h
- headers/tchk.h
- model_gen.tcl
- src/main.cpp
- src/vpi_user.cpp
- templates/vpi_user.cpp
> vpiParent and vpi_handle support

- model_gen.tcl
- src/Serializer.cpp
- templates/Serializer.cpp
> capnp support

- model_gen.tcl
> return const ref for strings

- model/instance.yaml
- model_gen.tcl
- templates/class_header.h
- tests/test1.cpp
> final, override and plural for "any" members

- model_gen.tcl
- templates/class_header.h
> disable object factory for virtual classes

- CMakeLists.txt
- tests/dump.cpp
- tests/test1.cpp
> add uhdm-dump utility

- model_gen.tcl
- templates/vpi_uhdm.h
> Remove some casting in vpi_user.cpp and reformat

- model_gen.tcl
- templates/Serializer.h
- templates/Serializer_save.cpp
- templates/class_header.h
- templates/vpi_uhdm.h
> return const pointers for getter methods

- model_gen.tcl
- templates/vpi_uhdm.h
> SymbolFactory::ID

- model_gen.tcl
- templates/Serializer.h
- templates/Serializer_restore.cpp
- templates/Serializer_save.cpp
- templates/class_header.h
- templates/uhdm.h
- templates/uhdm_types.h
- templates/vpi_uhdm.h
- templates/vpi_user.cpp
> Use an enum for uhdm types

- model_gen.tcl
- templates/BaseClass.h
- templates/Serializer.h
- templates/Serializer_restore.cpp
- templates/Serializer_save.cpp
- templates/SymbolFactory.cpp
- templates/SymbolFactory.h
- templates/class_header.h
- templates/containers.h
- templates/group_header.cpp
- templates/uhdm_types.h
- templates/vpi_uhdm.h
- templates/vpi_user.cpp
> Cleanup headers

- CMakeLists.txt
- Makefile
> Use install location as provided by CMake, not a hardcoded path.

- Makefile
> Only run cmake if needed.

- model/constant.yaml
- model/delay_control.yaml
- model/expr.yaml
- model/models.lst
- model_gen.tcl
- templates/vpi_user.cpp
- templates/vpi_visitor.cpp
- tests/test3.cpp
> Support for vpi_get_value and vpi_get_delay

- CMakeLists.txt
- README.md
- model/cont_assign.yaml
- model/cont_assign_bit.yaml
- model/delay_control.yaml
- model/enum_const.yaml
- model/expr.yaml
- model/expr_dist_group.yaml
- model/func_call.yaml
- model/interface.yaml
- model/module.yaml
- model/parameter.yaml
- model/prim_term.yaml
- model/primitive.yaml
- model/program.yaml
- model/var_select.yaml
- model/variables.yaml
- model_gen.tcl
> Update model with vpi_get_value

- model/func_call.yaml
- model/method_func_call.yaml
- model/method_func_task_call_group.yaml
- model/method_task_call.yaml
- model/models.lst
- model/sys_func_call.yaml
- model/sys_func_task_call_group.yaml
- model/tf_call.yaml
- model/tf_call_args.yaml
- model/with_expr_constr_group.yaml
- model_gen.tcl
Fixes #134.
I'm opening this as a draft to have a place for discussions.
> [WIP] Add system call model

- CMakeLists.txt
- model/func_call.yaml
- model/method_func_task_call_group.yaml
- model/models.lst
- model/tf_call_args.yaml
- tests/test_tf_call.cpp
> Add tests of tf_call

- templates/uhdm_types.h
Makes client C++ code with less casts
> Changed any from void to BaseClass

- tests/test_tf_call.cpp
Adresses https://github.com/alainmarcel/UHDM/pull/145#pullrequestreview-369704826.
> Change file name in test_tf_call

- CMakeLists.txt
- model/delay_term.yaml
- model/event_control.yaml
- model/expr_sequence_inst_named_event_group.yaml
- model/expr_tchk_term_group.yaml
- model/models.lst
- model/process.yaml
- model/simple_expr_use_group.yaml
- model/stmt.yaml
- model/tchk.yaml
- model/tchk_term.yaml
- tests/test_process.cpp
> Expand process model

- model_gen.tcl
Made some initial changes to model_gen. Still few things left to look at.
> First round of edits of model_gen

- model/bit_select.yaml
Signed-off-by: Alain Dargelas <alainmarcel@yahoo.com>
> bit select

- README.md
Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>
> DO NOT MERGE - Testing Kokoro

- model_gen.tcl
- templates/BaseClass.h
- templates/vpi_user.cpp
- tests/test1.cpp
- tests/test3.cpp
- tests/test_process.cpp
> vpi_handle_by_name support

- .travis.yml
> Update travis: install cmake and see version.

- .gitignore
- CMakeLists.txt
- model_gen/model_gen.tcl
- templates/Serializer_restore.cpp
- templates/Serializer_save.cpp
- templates/SymbolFactory.cpp
- tests/dump.cpp
Issue #210
Add support for Windows/Mac
Resolution
Updated CMakeLists.txt to build on Windows using MSVC compiler.
Known Issues
* Lots of warnings, needs attention.
* Only the build operation is verified i.e. the code may still not run
successfully.
> Issue #210: Add support for Windows/Mac

- tests/dump.cpp
Also, output the normal operation headers to cout, as the Surelog regression tcl script would otherwise complain about things coming to stderr.
> Directly output to stream

- .editorconfig
> Encode some simple style-rules in .editorconfig

- model/instance.yaml
- model/let_expr.yaml
> Fix typos in YAML files.

- CMakeLists.txt
- model_gen/parse_model.tcl
> Report errors in yaml files: exit 1 on invalid lines.

- templates/Serializer.h
- templates/Serializer_save.cpp
> Serializer::save(): use const string reference parameter.

- model/gen_scope.yaml
- model/instance.yaml
- model/tchk.yaml
> Fix some class_ref which should've been obj_ref.

- model/named_event.yaml
> Fix reference (class_ref -> obj_ref): event_typespec is an obj_def

- CMakeLists.txt
- templates/vpi_user.cpp
Fixing build issues on windows platform
> Fix Windows build

- .travis.yml
- CMakeLists.txt
- Makefile
- templates/vpi_user.cpp
Adding CI support for Windows platform
> Issue #229: Windows CI support

- model_gen/model_gen.tcl
Issue #826: Prevent func_call from stepping/visiting Function
Issue:
Recursive functions end up being infinite loops.
Cause:
VPIListener and vpi_listener both had the logic to step into
vpiFunction types when encountering a vpiFunc_call.
Resolution:
Don't let vpiFunc_call step/visit vpiFunction and instead let
the code flow i.e. the structure of the code in file in question
dictate when the specific function is stepped-into/visited.
> Issue#826 - Prevent func_call from stepping.visiting Function

- .github/workflows/main.yml
- CMakeLists.txt
Fixed link issue in MSYS builds and re-enable MSYS configuration for CI
> Enable MSYS

- model/create_model.tcl
- model_gen/generate_elaborator.tcl
- model_gen/model_gen.tcl
- model_gen/parse_model.tcl
> Fix Tcl indentation and remove trailing whitespace.

- CMakeLists.txt
> Sort sort filenames in CMakeLists to easier find them.

- .github/workflows/main.yml
- .gitignore
- CMakeLists.txt
- Makefile
- model_gen/model_gen.tcl
Reverts chipsalliance/UHDM#485
Please fix the Surelog build issues.
> Revert "Put all generated code in the build/ directory."

- .github/workflows/main.yml
> Add a CI build and test for MacOS

- .github/workflows/main.yml
- Makefile
> Up the fallback assumption of available cores to two.

- CMakeLists.txt
- templates/Serializer_save.cpp
> Fix garbage collect test.

- CMakeLists.txt
- model_gen/generate_elaborator.tcl
- model_gen/model_gen.tcl
- scripts/generate.py
- templates/BaseClass.h
- templates/RTTI.h
- templates/class_header.h
- templates/clone_tree.cpp
Issue #1727 - Surelog parsing seems pretty slow
Introducing custom implementation of dynamic_cast to speed
up things.
> Issue #1727 - Surelog parsing seems pretty slow

- .github/workflows/main.yml
- CMakeLists.txt
- tests/testErrorHandler.cpp
Issue #510: Add matrix to test different script code generations
Updated the workflow to build using both tcl and python generators.
Also, fixing broken build.
>  Issue #510: Add matrix to test different script code generations

- model_gen/model_gen.tcl
- scripts/classes_h.py
- scripts/serializer.py
- scripts/vpi_user_cpp.py
- templates/BaseClass.h
- templates/ElaboratorListener.h
- templates/ExprEval.cpp
- templates/Serializer.h
- templates/Serializer_restore.cpp
- templates/Serializer_save.cpp
- templates/SymbolFactory.cpp
- templates/SymbolFactory.h
- templates/clone_tree.cpp
- templates/group_header.cpp
- templates/uhdm_types.h
- templates/vpi_uhdm.h
- templates/vpi_user.cpp
- tests/full_elab_test.cpp
- tests/listener_elab_test.cpp
- tests/vpi_listener_test.cpp
Memory Optimization Pass
Use std::string_view in place of std::string in SymbolFactory.
Updated all code generation scripts to use std::string_view.
> Memory Optimization Pass

- model_gen/model_gen.tcl
- scripts/classes_h.py
- scripts/serializer.py
- scripts/vpi_user_cpp.py
- templates/BaseClass.h
- templates/ElaboratorListener.h
- templates/ExprEval.cpp
- templates/Serializer.h
- templates/Serializer_restore.cpp
- templates/Serializer_save.cpp
- templates/SymbolFactory.cpp
- templates/SymbolFactory.h
- templates/clone_tree.cpp
- templates/group_header.cpp
- templates/uhdm_types.h
- templates/vpi_uhdm.h
- templates/vpi_user.cpp
- tests/full_elab_test.cpp
- tests/listener_elab_test.cpp
- tests/vpi_listener_test.cpp
Reverts chipsalliance/UHDM#517.
Sorry, this changelist, along with the one in Surelog, is not compatible with my changelist from this week-end.
Please fix.
> Revert "Memory Optimization Pass"

- templates/ExprEval.cpp
Reverts chipsalliance/UHDM#522
> Revert "pattern assign"

- model_gen/generate_elaborator.tcl
@hs-apotell  to port in Python
> prevent elab loop in disable stmt

- model_gen/generate_elaborator.tcl
- scripts/ElaboratorListener_h.py
- templates/clone_tree.cpp
@hs-apotell I also modified the .py files when it's easy to find the equivalent change
> task and func deep cloning

- CMakeLists.txt
Reverts chipsalliance/UHDM#550
> Revert "Use precompiled headers to improve build times."

- model/checker_decl.yaml
- model/checker_inst.yaml
- model/checker_inst_port.yaml
- model/checker_port.yaml
- model/models.lst
- templates/uhdm_vpi_user.h
The checker model is omitted from the Standard, creating one.
> Custom checker model

- model_gen/model_gen.tcl
- model_gen/parse_model.tcl
- scripts/classes.py
Transitive Grouping
Implement transitive grouping in python and also simplify the logic
in tcl script.
> Transitive Grouping

- model_gen/model_gen.tcl
- model_gen/parse_model.tcl
- scripts/classes.py
- scripts/vpi_listener.py
- scripts/vpi_user_cpp.py
- templates/Serializer.h
- templates/uhdm.h
- templates/vpi_listener.cpp
- templates/vpi_listener.h
- tests/full_elab_test.cpp
- tests/listener_elab_test.cpp
- tests/vpi_listener_test.cpp
Few tweaks and fixing a few warnings
> Few tweaks and fixing a few warnings

- .github/workflows/main.yml
- CMakeLists.txt
- tests/vpi_listener_test.cpp
Deprecate Tcl based code generation
Updated CMakeLists.txt & workflow file to remove usage and references to Tcl.
> Deprecate Tcl based code generation

- INSTALL.md
> Document needed Python orderedmultidict dependency

- scripts/ElaboratorListener_cpp.py
- scripts/VpiListenerTracer_h.py
- scripts/VpiListener_h.py
- scripts/capnp.py
- scripts/classes.py
- scripts/clone_tree_cpp.py
- scripts/containers_h.py
- scripts/file_utils.py
- scripts/loader.py
- scripts/serializer.py
- scripts/uhdm_forward_decl_h.py
- scripts/uhdm_h.py
- scripts/uhdm_types_h.py
- scripts/vpi_listener.py
- scripts/vpi_user_cpp.py
- scripts/vpi_visitor_cpp.py
Writeable files are only in the build output.
> Don't open read-only inputs with read/write.

- .github/workflows/main.yml
- CMakeLists.txt
- scripts/capnp.py
- scripts/classes.py
- scripts/serializer.py
- scripts/uhdm_forward_decl_h.py
- templates/ElaboratorListener.cpp
- templates/ElaboratorListener.h
- templates/Serializer.cpp
- templates/Serializer.h
- templates/Serializer_restore.cpp
- templates/VpiListener.h
- templates/VpiListenerTracer.h
- templates/class_source.cpp
- templates/clone_tree.h
- templates/containers.h
- templates/group_header.h
- templates/uhdm_forward_decl.h
- templates/vpi_uhdm.h
- templates/vpi_visitor.h
Reverts chipsalliance/UHDM#635
> Revert "Issue chipsalliance/UHDM#628: Reduce library size & improve build times"

- .github/workflows/main.yml
- CMakeLists.txt
- scripts/capnp.py
- scripts/classes.py
- scripts/serializer.py
- scripts/uhdm_forward_decl_h.py
- templates/ElaboratorListener.cpp
- templates/ElaboratorListener.h
- templates/Serializer.cpp
- templates/Serializer.h
- templates/Serializer_restore.cpp
- templates/VpiListener.h
- templates/VpiListenerTracer.h
- templates/class_source.cpp
- templates/clone_tree.h
- templates/containers.h
- templates/group_header.h
- templates/uhdm_forward_decl.h
- templates/vpi_uhdm.h
- templates/vpi_visitor.h
Reverts chipsalliance/UHDM#637
> Revert "Revert "Issue chipsalliance/UHDM#628: Reduce library size & improve build times""

- .github/workflows/main.yml
- CMakeLists.txt
- scripts/capnp.py
- scripts/classes.py
- scripts/serializer.py
- scripts/uhdm_forward_decl_h.py
- templates/ElaboratorListener.cpp
- templates/ElaboratorListener.h
- templates/Serializer.cpp
- templates/Serializer.h
- templates/Serializer_restore.cpp
- templates/UhdmLint.cpp
- templates/UhdmLint.h
- templates/VpiListener.h
- templates/VpiListenerTracer.h
- templates/class_source.cpp
- templates/clone_tree.h
- templates/containers.h
- templates/group_header.h
- templates/uhdm_forward_decl.h
- templates/vpi_uhdm.h
- templates/vpi_visitor.h
Reverts chipsalliance/UHDM#641
> Revert "lint check unsized packed dim"

- scripts/classes.py
chipsalliance/UHDM#652: Infinite loop in comparison logic
Blacklist vpiInstance relation so it gets ignored during comparison
> chipsalliance/UHDM#652: Infinite loop in comparison logic

- scripts/VpiListener_h.py
- scripts/vpi_listener.py
- templates/ElaboratorListener.cpp
- templates/ElaboratorListener.h
- templates/ExprEval.cpp
- templates/SynthSubset.cpp
- templates/SynthSubset.h
- templates/clone_tree.cpp
Fix a few location issues with clones
> Fix a few location issues with clones

- scripts/UhdmListener.py
Align callbacks in UhdmListener with VpiListener so they can be used interchangeably.
> Align VpiListener & UhdmListener

- shell.nix
> Add shell.nix to provide all necessary build requirements.

- CMakeLists.txt
Fix use of WITH_LIBCXX flag and default it to OFF
> Fix use of WITH_LIBCXX flag and default it to OFF

- model/include_file_info.yaml
- templates/uhdm_vpi_user.h
chipsalliance/Surelog#2541: Add include file info model
UHDM::design now provides a list of includes
> chipsalliance/Surelog#2541: Add include file info model

- templates/vpi_visitor.cpp
Reverts chipsalliance/UHDM#723
> Revert "Issue chipsalliance/Surelog#2985: Remove 'parent' in uhdm output"

- scripts/classes.py
- templates/ElaboratorListener.cpp
- templates/ElaboratorListener.h
Reverts chipsalliance/UHDM#727 temporarily
> Revert "Fix High_conn binding bug"

- templates/RTTI.h
- templates/Serializer_restore.cpp
- templates/Serializer_save.cpp
- templates/UhdmListener.cpp
- templates/uhdm.h
- templates/vpi_user.cpp
- templates/vpi_visitor.cpp
- tests/expr_reduce_test.cpp
- tests/group_membership_test.cpp
> Remove superfluous <map> includes.

- templates/Serializer_save.cpp
> Don't copy strings if not needed.

- model/instance_array.yaml
- templates/ElaboratorListener.cpp
Add typespec for interface_array
> Add typespec for interface_array

- templates/ExprEval.cpp
Handle null expressions in case_item. In case of 'default' this would be null.
> Handle null expressions in case_item. In case of 'default' this would be null.

- templates/Serializer.cpp
- templates/Serializer.h
> Print formatted stats

- include/sv_vpi_user.h
- model/instance_array.yaml
- model/models.lst
- model/module_typespec.yaml
- scripts/ElaboratorListener_cpp.py
Adding support for interface_array & module_array in non-elab model
> Adding support for interface_array & module_array in non-elab model

- templates/ExprEval.cpp
- templates/ExprEval.h
Remove unused filename and linenumber params and fixed a few warnings
> Remove unused filename and linenumber params and fixed a few warnings

- templates/ExprEval.cpp
Since sizes got fixed not long ago, removing safeguard.
> concat with dec radix

- templates/ExprEval.cpp
- templates/UhdmLint.cpp
Code maintenance
* Don't clone strings where not necessary
* Use nullptr instead of 0
* Use std::string::find instead of strstr
* When looking for type prefixes, look for prefix instead of anywhere in the string
* Avoid iterations where unnecessary
* Use any_cast instead of dynamic_cast
> Code maintenance

- templates/SynthSubset.cpp
- templates/SynthSubset.h
Give specific message for a task when it is non-synthesizable.
> Synthesizable tasks

- CMakeLists.txt
- scripts/classes.py
- util/uhdm-cmp.cpp
Introducing uhdm-cmp tool to topographically compare two uhdm binaries
Also, fixed a few issues identified while testing the comparison logic generated by the scripts.
> Introducing uhdm-cmp tool to topographically compare two uhdm binaries

- scripts/ElaboratorListener_cpp.py
Need to remove the module cont_assign since they already are in the instance tree
> cont_assign present in Surelog elab tree

- templates/SynthSubset.cpp
Signed-off-by: Henner Zeller <hzeller@google.com>
> Add missing break in switch statement.

- templates/ExprEval.cpp
Fixed a few type conversion warnings in ExprEval
> Fixed a few warnings

- CMakeLists.txt
- templates/ExprEval.cpp
- templates/ExprEval.h
- tests/expr_prettyPrint_test.cpp
Pull request for ExprVal::prettyPrint update
> ExprVal::prettyPrint update

- CMakeLists.txt
Only use git to extract a commit hash if available.
> Always extract version number from cmake project

- .github/workflows/main.yml
- Makefile
> Add a test target to determine if pkg-config is complete.

- CMakeLists.txt
This will also be a test if the auto-tagging on merge will work.
> Bump version to 1.49

- .github/workflows/main.yml
> Set permissions to write tag.

- CMakeLists.txt
xref: https://github.com/chipsalliance/UHDM/pull/891
@hzeller
> install shared libraries in same folder as static libraries

- CMakeLists.txt
> Bump version: 1.50

- CMakeLists.txt
- include/config.h.in
Add a project scope config header
> Add a project scope config header

- templates/ExprEval.cpp
This PR adds support of flattening nested assignment patterns.
Surelog PR: https://github.com/chipsalliance/Surelog/pull/3601
> Support flatten of nested assignment patterns

- .github/workflows/main.yml
- Makefile
- README.md
Fix https://github.com/chipsalliance/UHDM/issues/901
> Fix workflow to run python tests & contribute to documentation

- scripts/classes.py
- scripts/vpi_visitor_cpp.py
- templates/ExprEval.cpp
- templates/SynthSubset.cpp
- templates/clone_tree.cpp
- templates/vpi_visitor.cpp
- templates/vpi_visitor.h
* Decorative change to assist with debugging in generated model files
* Fixed a few warnings related to unreachable code
* Redo vpi visitor to avoid recurrent public api changes
> Redo vpi visitor logic to avoid recurrent api changes

- scripts/ElaboratorListener_cpp.py
- templates/ElaboratorListener.cpp
- templates/ElaboratorListener.h
- templates/ExprEval.cpp
- templates/clone_tree.cpp
> Fixing parenting issues

- model/assert_stmt.yaml
- model/assume.yaml
- model/cover.yaml
- model/immediate_assert.yaml
- model/immediate_assume.yaml
- model/immediate_cover.yaml
- model/property_inst.yaml
- model/restrict.yaml
- model/sequence_inst.yaml
- scripts/classes.py
- templates/BaseClass.h
- templates/ElaboratorListener.cpp
- templates/ExprEval.cpp
- templates/UhdmAdjuster.cpp
- templates/UhdmLint.cpp
- templates/clone_tree.cpp
Generated model file improvements
* Remove duplicate location information in models
* Add mutable API to generated model files
* Adding templated accessors. Updated UhdmLint as an example to show case its use.
* Fixed a few warnings from windows build (mostly about hiding local variable definitions)
> Generated model file improvements

- templates/UhdmLint.cpp
Issue chipsalliance/Surelog#3708: Report final wire assignments as illegal
> Issue chipsalliance/Surelog#3708: Report final wire assignments as illegal

- CMakeLists.txt
> Upgrade cap'n'proto to head

- util/uhdm-dump.cpp
Option to print statistics
Added an option to print object statistics (count per type).
> Option to print statistics

- .github/workflows/main.yml
> Lock capnproto to v1.0.0

- templates/ExprEval.cpp
Issues #3862, #3863: Typespec assignment problems
* Handle "returnTypespec" param correctly
* Set Typespec when handling io_decls
* Handle packed_array_typespec as well when handling array_tyespec
> Issues #3862, #3863: Typespec assignment problems

- templates/UhdmLint.cpp
Handle null references gracefully
> Handle null references gracefully

- CMakeLists.txt
> Upgrade to version 1.75

- templates/SynthSubset.cpp
Reverts chipsalliance/UHDM#1062
> Revert "filter packed_array_var"

- templates/SynthSubset.cpp
Reverts chipsalliance/UHDM#1061
> Revert "mem inference fix"

- CMakeLists.txt
- python/CMakeLists.txt
https://github.com/conda-forge/uhdm-feedstock/blob/main/recipe/fix_cmake.diff
https://github.com/conda-forge/uhdm-feedstock/blob/main/recipe/multiple_python.diff
https://github.com/conda-forge/uhdm-feedstock/blob/main/recipe/no_link_libpython.diff
> Apply patches from conda-forge

- .github/workflows/main.yml
- scripts/UhdmListener.py
- scripts/VpiListener.py
- templates/UhdmListener.cpp
- templates/VpiListener.cpp
- templates/VpiListener.h
- tests/listener_elab_test.cpp
- tests/uhdm_listener_test.cpp
- tests/vpi_listener_test.cpp
chipsalliance/UHDM#1095: Get implementation of UhdmListener & VpiListener in sync
> chipsalliance/UHDM#1095: Get implementation of UhdmListener & VpiListener in sync

- .github/workflows/main.yml
- scripts/UhdmListener.py
- scripts/VpiListener.py
- templates/UhdmListener.cpp
- templates/VpiListener.cpp
- templates/VpiListener.h
- tests/listener_elab_test.cpp
- tests/uhdm_listener_test.cpp
- tests/vpi_listener_test.cpp
Reverts chipsalliance/UHDM#1096 for diagnostic, will remerge if OK.
> Revert "chipsalliance/UHDM#1095: Get implementation of UhdmListener & VpiListener in sync"
